### ISSUE TITLE
Fix end-to-end test(Github actions)

### ISSUE THREAD

**Issue by ledyba-z** [SDWebImage/SDWebImageAVIFCoder#12]

**Comment by ledyba-z** [comment]
I would like to assign myself....

**Comment by dreampiggy** [comment]
It's OK..

And, I invite you to the contributor of SDWebImageAVIFCoder repo. You can submit the PR, and then merge if all the testing passing.

Seems you have already contribute the code more than me :)

Note for the release (via Git tag or CocoaPods trunk push) still need my help, if you find new PRs and features ready for release, please @me, I'll update the version of that.

**Comment by ledyba-z** [comment]
> Seems you have already contribute the code more than me :)

Haha, thank you!

> Note for the release (via Git tag or CocoaPods trunk push) still need my help

OK!

**Comment by ledyba-z** [comment]
https://github.com/AOMediaCodec/libavif/pull/98 (already mereged) and #13 may resolve this issue.

https://github.com/AOMediaCodec/libavif/pull/98 ships with libavif v0.6.0 (that contains some breaking changes).
