### ISSUE TITLE
'avif/avifs.h' file not found

### ISSUE THREAD

**Issue by quentinfasquel** [SDWebImage/SDWebImageAVIFCoder#33]
With a simple iOS project on Xcode, adding the package, adding the library on the target, adding "import" in code, using... getting a build issue that's just that.

**Comment by dreampiggy** [comment]
CocoaPods ? Or SwiftPM

Provide a simple demo is better.

**Comment by mokemoko** [comment]
I encountered the same problem with SwitfPM.
The error occurred in here (https://github.com/SDWebImage/SDWebImageAVIFCoder/blob/master/SDWebImageAVIFCoder/Classes/SDImageAVIFCoder.m#L16). Perhaps it is typo with `avif/avif.h`?

**Comment by dreampiggy** [comment]
Not typo. The old version of libavif, has a public header `avifs.h`, which means **AVIF Sequence**.

It include the animated avif (in draft) strcture declarations.

Seems when I update the libavif itself, it rename this file, I'll try to make compatible with the new avif version.

**Comment by dreampiggy** [comment]
Oh, seems actually typo. The `avifs.h` already been renamed in old version and I use that `avif.h` umbrella header instead. Seems the else case of `#if __has_include(<libavif/avif.h>)` fail in SwiftPM and run into this.

**Comment by dreampiggy** [comment]
@[quentinfasquel](https://github.com/quentinfasquel) @[mokemoko](https://github.com/mokemoko) Fix build issue in [v0.9.2](https://github.com/SDWebImage/SDWebImageAVIFCoder/releases/tag/0.9.2)
