### ISSUE TITLE
Could you upgrade libavif to v0.10.1?

### ISSUE THREAD

**Issue by wensbo** [SDWebImage/SDWebImageAVIFCoder#36]
Hi,
Could you upgrade libavif to v0.10.1?
I see a lot of updates in v0.10.0.
Among them, dav1d 1.0.0 has been released.

**Comment by dreampiggy** [comment]
Hope there are no huge API breaks..🙏

**Comment by wensbo** [comment]
If libavif-Xcode updates to the latest version, will we automatically synchronize the latest version as well.

**Comment by wensbo** [comment]
libavif-Xcode has been updated to v0.10.1, When will SDWebImageAVIFCoder be updated?

**Comment by wensbo** [comment]
Does SDWebImageAVIFCoder need to be changed, I introduced the latest version and found no problems

**Comment by dreampiggy** [comment]
NO

**Comment by wensbo** [comment]
thank you so much
