### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by wensbo** [SDWebImage/SDWebImageAVIFCoder#38]
<img width="450" alt="截屏2022-08-01 11 29 32" src="https://user-images.githubusercontent.com/17174309/182066851-fc2d5fae-2d1e-4790-9504-ff660e55bff5.png">

The sd library also did not receive memory warnning, so the cache is not cleared

<img width="1301" alt="截屏2022-07-30 20 12 58" src="https://user-images.githubusercontent.com/17174309/181913793-cd0c2d94-b3e2-4d62-96c9-001523a520c5.png">

When I comment out this code, it crashes.

**Comment by wensbo** [comment]
<img width="1301" alt="截屏2022-07-30 20 12 58" src="https://user-images.githubusercontent.com/17174309/181914239-c6d267a1-c896-4353-b604-be001bdd0019.png">

When i do this, all is ok.

**Comment by dreampiggy** [comment]
Should be fixed in #40.

**Comment by dreampiggy** [comment]
Released in [v0.9.3](https://github.com/SDWebImage/SDWebImageAVIFCoder/releases/tag/0.9.3)
