### ISSUE TITLE
Is Swift Package version still available?

### ISSUE THREAD

**Issue by wintersmoon** [SDWebImage/SDWebImageAVIFCoder#39]
Hi,
I'm trying to integrate it with Swift Package, but Xcode told me "The remote repository could not be accessed".
I can't access it(https://github.com/SDWebImage/SDWebImageAVIF.git) on GitHub either.
Could you please look into this issue, thanks.

**Comment by dreampiggy** [comment]
Typo. Change into repo url and try again.
`https://github.com/SDWebImage/SDWebImageAVIFCoder.git`
