### ISSUE TITLE
animated image memory leak

### ISSUE THREAD

**Issue by ifbowen** [SDWebImage/SDWebImageAVIFCoder#45]
![截屏2022-12-14 15 21 10](https://user-images.githubusercontent.com/17174309/207531392-f69bc0ce-d428-4c8d-a2bd-fd29c9676ad2.png)

**Comment by dreampiggy** [comment]
You can submit a PR to quick fix this, adding `CGImageRelease` after line of `#endif`

**Comment by ifbowen** [comment]
I submit a PR submit a PR to quick fix this. Can you merge it

**Comment by dreampiggy** [comment]
Released https://github.com/SDWebImage/SDWebImageAVIFCoder/releases/tag/0.9.4
