### ISSUE TITLE
About SDImageCoderDecodeThumbnailPixelSize & SDImageCoderDecodePreserveAspectRatio

### ISSUE THREAD

**Issue by MarvinShawn** [SDWebImage/SDWebImageAVIFCoder#49]
Nice day :)
wonder how to handle **SDImageCoderDecodeThumbnailPixelSize**  and **SDImageCoderDecodePreserveAspectRatio** passed by options when call ```- (UIImage *)decodedImageWithData:(NSData *)data options:(nullable SDImageCoderOptions *)options```

**Comment by dreampiggy** [comment]
See documentation...It's used when your web image url's own image size (like 400x300), does not match the desired size you want and how we scale down.

`ThumbnailPixelSize`: pass a CGSize, like (200, 200)
`PreserveAspectRatio`: pass bool, default true, means always scale aspect fit, else will scale to fit

For this case, that `400x300` will scaled down keeping aspect ratio to `200x150`

**Comment by dreampiggy** [comment]
That SDWebImageAVIFCoder need update for this support. The codec plugins need update when SDWebImage Core prodide new options, but I miss that AVIF one

**Comment by dreampiggy** [comment]
Suppoted in v0.10.0

There are still more to do, SDWebImage coder plugin feature (WebPCoder, for example) support like:

+ Animated AVIF encoding
+ Thumbnail Encoding


But I don't have enough freetime to complete. If you're interested in, please help and PR
