### ISSUE TITLE
Some HDR contents can not render correctly using AVIFCoder

### ISSUE THREAD

**Issue by dreampiggy** [SDWebImage/SDWebImageAVIFCoder#54]
Sample: 
[example.avif.zip](https://github.com/SDWebImage/SDWebImageAVIFCoder/files/12047653/example.avif.zip)

+ Desired render result:

![image](https://github.com/SDWebImage/SDWebImageAVIFCoder/assets/6919743/0bf15f7d-acd2-4c82-9ca0-7c155a52208a)

+ Actual (using v0.10.0) render result:

![image](https://github.com/SDWebImage/SDWebImageAVIFCoder/assets/6919743/e3e7125a-bd36-4c14-bd6c-d697c491ee4c)

**Comment by weaming** [comment]
any update?

**Comment by dreampiggy** [comment]
I' have a try with libavif's `YUVToRGB16` convert method, instead of current conversion written using Apple's vImage.

**Comment by dreampiggy** [comment]
Seems this image use Color Space transfer function `AVIF_TRANSFER_CHARACTERISTICS_SMPTE2084`

which is not supported by CGColorSpace.


However, it supported by CVPixelBuffer and CoreVideo: https://developer.apple.com/documentation/corevideo/kcvimagebuffertransferfunction_smpte_st_2084_pq

**Comment by dreampiggy** [comment]
A stupid solution:

1. If we detect some color space or format can not supported by Apple's Image/Video Framework, then call `avifImageRGBToYUV`
2. For others, use the exists code which use vImageConvert and CGColorSpace to convert, seems faster

**Comment by dreampiggy** [comment]
😂 @ledyba-z 

![image](https://github.com/SDWebImage/SDWebImageAVIFCoder/assets/6919743/9195dc91-d3b1-4895-9300-fd0a2216b59e)

Seems this code is from you ?

I'll decide to revert back to old `avifImageRGBToYUV` (slow but work) and color space convert for those non-supported image. Any idea or can you have time for help ? Seems the color space convert is complicated beyond my knowledge.

**Comment by dreampiggy** [comment]
Should I hack to just use kCGColorSpaceITUR_2100_PQ in RGB instead ?
