### ISSUE TITLE
`AVIF_RESULT_NO_CODEC_AVAILABLE` when encoding AVIF files

### ISSUE THREAD

**Issue by mgenware** [SDWebImage/SDWebImageAVIFCoder#59]
I'm on latest 0.11.0. Couldn't get the README example code to work on macOS Sonoma:
```swift
    let lossyAVIFData = SDImageAVIFCoder.shared.encodedData(with: img, format: .AVIF, options: [.encodeCompressionQuality: 0.6])
    try lossyAVIFData?.write(to: dest)
```

<img width="794" alt="image" src="https://github.com/SDWebImage/SDWebImageAVIFCoder/assets/11565096/0d179456-af15-43fb-9b59-afe7d4951da2">

My current lock file:
```
  - SDWebImage (5.18.2):
    - SDWebImage/Core (= 5.18.2)
  - SDWebImage/Core (5.18.2)
  - SDWebImageAVIFCoder (0.11.0):
    - libavif/core (>= 0.11.0)
    - SDWebImage (~> 5.10)
```

It seems that libaom is missing from SDWebImageAVIFCoder dependencies.

As per SDWebImageAVIFCoder README:

> [aom](https://github.com/SDWebImage/SDWebImageAVIFCoder#aom) By default, libavif is built with [aom](https://aomedia.googlesource.com/aom/) codec support. aom is the first AV1 codec during the standard draft implementation. The aom support both decodinng and encoding

This seems not true anymore. The [libavif repo](https://github.com/AOMediaCodec/libavif) instead says "No AV1 codecs are enabled by default. Enable them by enabling any of the following CMake options (e.g. -DAVIF_CODEC_AOM=ON)".

**Comment by mgenware** [comment]
Seems like a regression introduced in `0.11.0`, `0.10.1` works fine.

**Comment by dreampiggy** [comment]
> ibavif/core 

This is not enough. Seems break change.


You at leat need 

```
pod 'libavif/aom`
```

**Comment by dreampiggy** [comment]
> [aom](https://github.com/SDWebImage/SDWebImageAVIFCoder#aom) By default

This is no-longer correct for CocoaPods. I'll change the readme. 

Previouslly `aom` actually default and `not avoidable`, even you don't want aom, it always download and link to your App, which is not we want. You can not disable aom

**Comment by dreampiggy** [comment]
@mgenware Please check the updated README again 🙏

https://github.com/SDWebImage/SDWebImageAVIFCoder/commit/10b939f7e576bdaeed781f449734c64ae744a689

**Comment by dreampiggy** [comment]
For your case, if you choose to use aom, use `pod 'libavif/libaom'` is ok

or if you want faster AVIF encoding (aom using C-based software encoding is slowwwwwww), use:

```
pod 'libavif', :subspecs => ['libdav1d', 'librav1e']
```

See our demo's Podfile:
https://github.com/SDWebImage/SDWebImageAVIFCoder/blob/master/Example/Podfile#L6

**Comment by mgenware** [comment]
Thanks for the update. Right, libaom is so slow it's barely usable on any apple devices at the moment. Will use rav1e instead.
