### ISSUE TITLE
libavif + rav1e not compatible with `use_frameworks!` dynamic linking

### ISSUE THREAD

**Issue by mgenware** [SDWebImage/SDWebImageAVIFCoder#61]
A minimal reproducible podfile:

```
use_frameworks!

target 'test' do
  pod 'SDWebImageAVIFCoder'
  pod 'libavif', :subspecs => [
    'librav1e'
  ]
end
```

Run `pod install`, got the following error:
```
The 'Pods-test' target has transitive dependencies that include statically linked binaries (.../Pods/librav1e/Mac/librav1e.framework)
```

**Comment by dreampiggy** [comment]
by design. rav1e is just pre-built framework. You can grab that and directly use. No need CocoaPods

**Comment by dreampiggy** [comment]
rav1e does not support dynamic linking. And I'm still really disagreeing to use dynamic lib on iOS


Use

use_framworis! :linkage => :static

**Comment by dreampiggy** [comment]
Actually, it's CocoaPods limit.

You can not use pre-built binary to suppory both dynamic linking and static linking switch.

**Comment by dreampiggy** [comment]
I can update the README about this...

Actually, both HEIFCoder and AVIFCoder will use librav1e
